### ISSUE TITLE
Expose temperature and humidity as sensors

### ISSUE THREAD

**Issue by myevit** [dahlb/ha_carrier#14]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/dahlb/ha_carrier/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Sensors

### Describe the solution you'd like

Expose temperature and humidity thermostat reading as sensors. 
I use average temperature in the house and termostat reading would be great to see.

### Describe alternatives you've considered

N/A

### Additional context

N/A

**Comment by dahlb** [comment]
fixed in https://github.com/dahlb/ha_carrier/commit/c246bd3b904c232db9164536ab93d72b51d13153 released as 1.20.0

**Comment by dfludwig** [comment]
Nice enhancement, but got this in the HA log after updating to 1.20.0:

Entity sensor.downstairs_zone_1_humidity (<class 'custom_components.ha_carrier.sensor.ZoneHumiditySensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('humidity') it is using; expected one of ['%']; Please update your configuration if your entity is manually configured, otherwise report it to the custom integration author.

**Comment by dahlb** [comment]
thanks, fixed in 1.20.1

**Comment by myevit** [comment]
Confirming all works
Thanks!
